// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPZMrNreW3MNGxQmzNyA9cjBlfWr3kqaw',
    appId: '1:637925982759:web:a0bd5c5f1fb6da9b8d0402',
    messagingSenderId: '637925982759',
    projectId: 'banbanhkem-91d4e',
    authDomain: 'banbanhkem-91d4e.firebaseapp.com',
    storageBucket: 'banbanhkem-91d4e.firebasestorage.app',
    measurementId: 'G-K1FKZ17H54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsse1iXfdFmkl_DElWDx1NhsTJ_2X3K5U',
    appId: '1:637925982759:android:ce9e265b22aca5c58d0402',
    messagingSenderId: '637925982759',
    projectId: 'banbanhkem-91d4e',
    storageBucket: 'banbanhkem-91d4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0sld5sU-M6-WgPs8yccb_DpCE-yQCsHs',
    appId: '1:637925982759:ios:d289a2736c8d36df8d0402',
    messagingSenderId: '637925982759',
    projectId: 'banbanhkem-91d4e',
    storageBucket: 'banbanhkem-91d4e.firebasestorage.app',
    iosBundleId: 'com.example.doanNhom5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0sld5sU-M6-WgPs8yccb_DpCE-yQCsHs',
    appId: '1:637925982759:ios:d289a2736c8d36df8d0402',
    messagingSenderId: '637925982759',
    projectId: 'banbanhkem-91d4e',
    storageBucket: 'banbanhkem-91d4e.firebasestorage.app',
    iosBundleId: 'com.example.doanNhom5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPZMrNreW3MNGxQmzNyA9cjBlfWr3kqaw',
    appId: '1:637925982759:web:5b7048e169f1ab678d0402',
    messagingSenderId: '637925982759',
    projectId: 'banbanhkem-91d4e',
    authDomain: 'banbanhkem-91d4e.firebaseapp.com',
    storageBucket: 'banbanhkem-91d4e.firebasestorage.app',
    measurementId: 'G-93YR04LH13',
  );
}
